---
title: "Changes in Policy Views Among U.S. Latinos and African-American Voters"
author: "Jose Altamirano"
description: "Ideological changes among Latinos and African-Americans from 2000-2020"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data showcasing policy views and political attitudes of Latino and African-American voters in the United States over the last twenty years. As educational attainment has increasingly become a sorting variable for partisanship among white voters, I want to explore the extent to which this is true for Latino and Black voters, too.

This project asks whether Latino and Black voters without a college degree have become more conservative in their policy views towards immigration and race relations over the last twenty years, controlling for income and party registration.

To investigate this relationship, we are relying on data from three different sources:

1. [American National Election Studies (ANES) Survey](https://electionstudies.org/) time series data on electoral behavior and political participation. 

2. [Coooperative Election Study (CES)](https://cces.gov.harvard.edu/) data on policy opinions and 

3. precinct and CD-level electoral data from minority-majority districts to track Latino and Black voter behavior. 




